included:
  - XCloneApp
  - XCloneAppTests
  - XCloneAppUITests

excluded:
  - Pods
  - Carthage
  - DerivedData

disabled_rules:
  - line_length
  - cyclomatic_complexity
  - trailing_whitespace
  - unused_closure_parameter
